//Author: Micah West
//Date: 10/31/2017
//Purpose: Exception thrown when there is an incorrect number of fields within a given record
//		   when considering the problem addressed by ProfileLauncher.java. Part of the solution to
//         Question 20. The code in this file was generated by Eclipse.
//Included files: ProfileLauncher.java, Profile.java, InvalidProfileFormatException.java
//Input: none
//Output: none

package com.revature.corejava.Q20;

public class InvalidProfileFormatException extends RuntimeException {

	private static final long serialVersionUID = -8488563570604456502L;
	
}
