//Author: Micah West
//Date: 10/31/2017
//Purpose: Store the profile info for a person and display it. Part of the solution for Question 20.
//Included files: ProfileLauncher.java, Profile.java, InvalidProfileFormatException.java
//Input: none
//Output: none

package com.revature.corejava.Q20;

public class Profile {
	
	private String firstName;
	private String lastName;
	private int age;
	private String state;
	
	
	public void displayPerson() {
		
		System.out.println("Name: " + firstName + " " + lastName);
		System.out.println("Age: " + age + " years.");
		System.out.println("State: " + state);
	}
	
	// All of the following methods were generated by Eclipse.
	public Profile(String firstName, String lastName, int age, String state) {
		
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.age = age;
		this.state = state;
	}

	public String getFirstName() {
		
		return firstName;
	}

	public void setFirstName(String firstName) {
		
		this.firstName = firstName;
	}

	public String getLastName() {
		
		return lastName;
	}

	public void setLastName(String lastName) {
		
		this.lastName = lastName;
	}

	public int getAge() {
		
		return age;
	}

	public void setAge(int age) {
		
		this.age = age;
	}

	public String getState() {
		
		return state;
	}

	public void setState(String state) {
		
		this.state = state;
	}
}
